### ISSUE TITLE
split this in multiple npms

### ISSUE THREAD

**Issue by mwawrusch** [stolsma/authpack#1]
Hi there,
thanks a lot for putting a lot of effort into this. It is very helpful for me. May I suggest that you consider splitting this into multiple npms? It makes usage and contributing much easier, and often simplifies testing as well. A good example for this would be passport (passportjs.org). Perhaps one for the client side, one for the overall server, and one with the server building blocks?

Martin

**Comment by stolsma** [comment]
Hi Martin!

Thanks for your comments!! It's also a learning project for me so if you have more comments just put them in more issues!! :-)

Regarding splitting, the text of the README is a little deceptive as I wasn't considering writing client code (although it states the package will..). As you said, passport and everyauth are much better in that.... ;-)

Authpack will only consist of OAuth2, OpenId Connect and UMA building blocks with some basic server examples to show how to use those building blocks. The current oauth2/index.js server code is more or less a stopgap until the lower building blocks are ready and I have time to create a consistent example.

BTW I will accept reasonable pull requests on this code so if you have some please send them in... ;-)

Sander

**Comment by mwawrusch** [comment]
I will. Right now I am learning from your code :) 

BTW, check out my board here: http://www.quora.com/Martin-Wawrusch/Oauth-2-Resources-For-Provider-Implementers
I am trying to collect all available resources for implementers of oauth2 providers.

**Comment by stolsma** [comment]
Nice overview on that page! 

In the future this package needs some overview references too, I will keep the url to your board in my archive for that! :-)

**Comment by stolsma** [comment]
@mwawrusch 

I changed the code to a building block setup and implemented events to communicate out of the main OAuth2 server class to the implementation specific authentication and authorization 'plugins'. Let me know if you like this.

**Comment by mwawrusch** [comment]
Thx. I will look into this in detail next week. I have a working backend store for tokens, apps/clients and stuff and I am going to try to test it against your code.
