### ISSUE TITLE
script in package.json for vows needs path

### ISSUE THREAD

**Issue by mwawrusch** [stolsma/authpack#2]
You might want to change the script test in package.json from

"test": "vows ...

to 

"test": "node_modules/.bin/vows

to make sure that you use the correct version and that it works with travis-ci.org (which I encourage you to use, it's free and great for nodejs)

**Comment by stolsma** [comment]
Ah, yep you are right!!! Will change that!! Thanks!!

Never used travis-ci although I heard the guys from Nodejitsu talking about it. I will have a look at how to implement their service!

**Comment by stolsma** [comment]
Implemented!
