### ISSUE TITLE
multiple response types

### ISSUE THREAD

**Issue by mwawrusch** [stolsma/authpack#3]
more of a question. I do not completely understand the behavior if multiple response_types are requested, and what this code here does:

 // Handle the different registered grant types, see 1.3/3.1.1 of OAuth2 Specs.
          var rt = self.responseTypes;
          for (var i=0; i < rt.length; i += 2) {
            if (rt[i][0] === options.response_type) return rt[i+1](req, res, options);
          }

A bit more explanation in the source would be great.

**Comment by mwawrusch** [comment]
argh, this oauth2 thing is driving me crazy. To answer my question: http://openid.net/specs/oauth-v2-multiple-response-types-1_0-03.html

**Comment by stolsma** [comment]
Yep, those standards documents are not easy to read and even harder to implement in real code.... :-(

Luckily you found the answer to your own question ;-) but you are right that its not very clear that the checkResponseType call (https://github.com/stolsma/authpack/blob/master/lib/oauth2/authorization-server.js#L73) and the code you referenced to are related to each other. In the future (its in the todo) the checkResponseType function will sort the response_type parameters in such a way that the corresponding execution function can be found directly... 

Maybe I have time to implement it tomorrow.

Again thanks for your remark, even though you found the answer yourself!! I sometimes had the idea that I was the only one not understanding the text in the rfc... ;-)
